- name: Symlink from Google Drive
  include_tasks:
    file: symlink.yaml
  loop:
    - src: "{{ ansible_env.HOME }}/Google Drive/Other computers/My iMac/Downloads"
      dest: "{{ ansible_env.HOME }}/Downloads"
    - src: "{{ ansible_env.HOME }}/Google Drive/Other computers/My iMac/Desktop"
      dest: "{{ ansible_env.HOME }}/Desktop"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/zprofile"
      dest: "{{ ansible_env.HOME }}/.zprofile"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/kube-config"
      dest: "{{ ansible_env.HOME }}/.kube/config"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/npmrc"
      dest: "{{ ansible_env.HOME }}/.npmrc"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/s3cfg"
      dest: "{{ ansible_env.HOME }}/.s3cfg"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/terraformrc"
      dest: "{{ ansible_env.HOME }}/.terraformrc"
  vars:
    _symlink_src: "{{ item.src }}"
    _symlink_dest: "{{ item.dest }}"
