- name: Symlink from Google Drive
  include_tasks:
    file: symlink.yaml
  loop:
    - src: "{{ ansible_env.HOME }}/Google Drive/Other computers/My iMac/Downloads"
      dest: "{{ ansible_env.HOME }}/Downloads"
    - src: "{{ ansible_env.HOME }}/Downloads/dotfiles/zprofile"
      dest: "{{ ansible_env.HOME }}/.zprofile"
  vars:
    _symlink_src: "{{ item.src }}"
    _symlink_dest: "{{ item.dest }}"
