- name: Check the current symlink
  ansible.builtin.stat:
    path: "{{ _symlink_dest }}"
  register: symlink_dest_stat

- name: Remove existing dest
  ansible.builtin.file:
    path: "{{ _symlink_dest }}"
    state: absent
  when: |
    symlink_dest_stat.stat.islnk is false or (symlink_dest_stat.stat.islnk is true and symlink_dest_stat.stat.lnk_target != _symlink_src)

- name: Create parent dest folder
  ansible.builtin.file:
    path: "{{ _symlink_dest | dirname }}"
    state: directory

- name: Create symlink
  ansible.builtin.file:
    path: "{{ _symlink_dest }}"
    src: "{{ _symlink_src }}"
    state: link
    force: yes
