homebrew_installed_packages:
  - act
  - ansible
  - asciidoc
  - autoconf
  - awscli
  - azure-cli
  - bash
  - bash-completion
  - bazelisk
  - buildifier
  - colordiff
  - coreutils
  - curl
  - delve
  - duti
  - homeport/tap/dyff
  - esolitos/ipa/sshpass
  - firebase-cli
  - gabrie30/utils/ghorg
  - git
  - git-lfs
  - gradle
  - go
  - golangci-lint
  - goreleaser
  - graphviz
  - gzip
  - helm
  - norwoodj/tap/helm-docs
  - helmfile
  - jenv
  - jq
  - less
  - k6
  - kind
  - ko
  - krew
  - azure/kubelogin/kubelogin
  - kubernetes-cli
  - kustomize
  - mas
  - maven
  - minio-mc
  - mysql-client
  - node@24
  - openssl
  - oven-sh/bun/bun
  - hashicorp/tap/packer
  - pandoc
  - pkg-config
  - pnpm
  - postgresql@18
  - poetry
  - redis
  - s3cmd
  - getsentry/tools/sentry-cli
  - skaffold
  - stern
  - telnet
  - hashicorp/tap/terraform
  - terragrunt
  - tree
  - daveshanley/vacuum/vacuum
  - hashicorp/tap/vault
  - watch
  - wget
  - xz
  - yarn
  - yq
  - zsh
  - zsh-history-substring-search

homebrew_cask_apps:
  #  - qbittorrent
  #  - stremio
  - adobe-acrobat-reader
  - airflow
  - chrome-remote-desktop-host
  - claude-code
  - docker-desktop
  - google-chrome
  - google-cloud-sdk
  - google-drive
  - hot
  - hubstaff
  - iterm2
  - jetbrains-toolbox
  - ledger-wallet
  - macai
  - mucommander
  - mysides
  - netdownloadhelpercoapp
  - postman
  - scroll-reverser
  - shifty
  - slack
  - steam
  - sublime-text
  - telegram
  - temurin
  - temurin@11
  - temurin@17
  - temurin@21
  - vlc
  - whatsapp
  - yubico-authenticator
  - zoom

homebrew_taps:
  - hashicorp/tap
  - homeport/tap
  - esolitos/ipa
  - gabrie30/utils
  - getsentry/tools
  - norwoodj/tap
  - oven-sh/bun
  - azure/kubelogin
  - daveshanley/vacuum
  - siderolabs/tap

mas_installed_apps:
  - id: 1475387142
    name: Tailscale (1.20.2)
  - id: 1352778147
    name: Bitwarden (1.30.0)

oh_my_zsh_plugins: [ ]

krew_plugins:
  - ctx
  - get-all
  - grep
  - iexec
  - ns
  - pexec
  - stern
  - view-secret

favourites:
  - name: Home
    path: ""
  - name: Workspace
    path: workspace

ssh_private_key: false
ssh_public_key: false

secret_profile: false

dotfiles:
  - src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  - src: .gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
  - src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  - src: ssh-config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
  - src: profile.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/profile.zsh"
  - src: iterm-profile.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/iterm-profile.json"
  - src: ghorg-conf.yaml
    dest: "{{ ansible_env.HOME }}/.config/ghorg/conf.yaml"
  - src: claude-settings.json
    dest: "{{ ansible_env.HOME }}/.claude/settings.json"
  - src: .npmrc
    dest: "{{ ansible_env.HOME }}/.npmrc"

ghorg:
  - name: slamdev
    scm: github
    cloneType: user
    path: "{{ ansible_env.HOME }}"
    outputDir: workspace/slamdev
    baseUrl: https://api.github.com/

jenv_plugins:
  - export
