homebrew_installed_packages:
  - ansible
  - autoconf
  - awscli
  - azure-cli
  - bash-completion
  - bazelisk
  - buildifier
  - colordiff
  - coreutils
  - curl
  - dyff
  - esolitos/ipa/sshpass
  - gabrie30/utils/ghorg
  - git
  - git-lfs
  - gradle
  - go
  - golangci-lint
  - goreleaser
  - graphviz
  - gzip
  - helm
  - helm-docs
  - helmfile
  - jenv
  - jq
  - less
  - k6
  - ko
  - krew
  - kubelogin
  - kubernetes-cli
  - kustomize
  - mas
  - maven
  - minio-mc
  - mysql-client
  - node@18
  - openssl
  - pkg-config
  - pnpm
  - postgresql
  - redis
  - s3cmd
  - skaffold
  - sshpass
  - stern
  - telnet
  - terraform
  - terragrunt
  - tree
  - vacuum
  - vault
  - watch
  - wget
  - xz
  - yarn
  - yq
  - zsh
  - zsh-history-substring-search

homebrew_cask_apps:
  - adobe-acrobat-reader
  - authy
  - chrome-remote-desktop-host
  - docker
  - google-chrome
  - google-cloud-sdk
  - google-drive
  - hot
  - hubstaff
  - iterm2
  - jetbrains-toolbox
  - mucommander
  - mysides
  - plex
  - postman
  - qbittorrent
  - scroll-reverser
  - shifty
  - skype
  - slack
  - stremio
  - sublime-text
  - telegram
  - temurin
  - temurin11
  - temurin17
  - vlc
  - whatsapp
  - yubico-yubikey-manager
  - zoom

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

mas_installed_apps:
  - id: 1475387142
    name: Tailscale (1.20.2)
  - id: 1352778147
    name: Bitwarden (1.30.0)

mas_email: false
mas_password: false
mas_signin_dialog: false

oh_my_zsh_plugins: [ ]

krew_plugins:
  - ctx
  - get-all
  - grep
  - iexec
  - ns
  - pexec
  - stern
  - view-secret

favourites:
  - name: Home
    path: ""
  - name: Workspace
    path: workspace

ssh_private_key: false
ssh_public_key: false

secret_profile: false

dotfiles:
  - src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  - src: .gitignore
    dest: "{{ ansible_env.HOME }}/.gitignore"
  - src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
  - src: ssh-config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
  - src: profile.zsh
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/profile.zsh"
  - src: iterm-profile.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/iterm-profile.json"
  - src: ghorg-conf.yaml
    dest: "{{ ansible_env.HOME }}/.config/ghorg/conf.yaml"
  - src: docker-config.json
    dest: "{{ ansible_env.HOME }}/.docker/config.json"

ghorg:
  - name: slamdev
    scm: github
    clone-type: user
    path: "{{ ansible_env.HOME }}"
    outputDir: slamdev
    base-url: https://api.github.com/

jenv_plugins:
  - export
