roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: gantsign.oh-my-zsh
    version: 2.4.0

collections:
  - name: geerlingguy.mac
    version: 1.4.0
  - name: community.general
    version: 4.8.0
