roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: gantsign.oh-my-zsh
    version: 2.7.0

collections:
  - name: geerlingguy.mac
    version: 2.2.0
  - name: community.general
    version: 7.3.0
